### ISSUE TITLE
Love it but configuration of new theme does not work

### ISSUE THREAD

**Issue by mach37** [mperdeck/dynamicbundles#3]
Hi, I love the dynamic bundling option.

Can you tell me - when I have new HTML theme, which contains overs 15 js libs and 10 css files, how does it parse out the libs. and how to configure them for auto-discovery.

Graci

**Comment by mperdeck** [comment]
Have a look at
http://getdynamicbundles.com

Your theme would probably sit in the LayoutContainer directory.

Not sure what you mean with "parse out the libs". However, you have the source code right here in this Github project, so maybe that can answer your question.
